### ISSUE TITLE
Error: onServerResponse is not defined

### ISSUE THREAD

**Issue by fabrice8** [xtravision-ai/xtravision-js-sdk#4]
Using the `xtravision-js-sdk.min.js`, I'm getting this error:

```JS
Uncaught ReferenceError: onServerResponse is not defined
    at s (xtravision-js-sdk.min.js:115:13594)
    at nv (xtravision-js-sdk.min.js:52:113163)
    at xtravision-js-sdk.min.js:52:148605
    at Xm (xtravision-js-sdk.min.js:52:149496)
    at HTMLUnknownElement.e (xtravision-js-sdk.min.js:39:2523)
    at Object.f (xtravision-js-sdk.min.js:39:2568)
    at b (xtravision-js-sdk.min.js:39:3469)
    at pb (xtravision-js-sdk.min.js:52:186136)
    at Qg (xtravision-js-sdk.min.js:52:179830)
    at Gg (xtravision-js-sdk.min.js:52:179673)
    at Dg (xtravision-js-sdk.min.js:52:178062)
    at Pg (xtravision-js-sdk.min.js:52:173957)
    at ow (xtravision-js-sdk.min.js:52:198180)
    at xtravision-js-sdk.min.js:52:202141
    at Lg (xtravision-js-sdk.min.js:52:178542)
    at Tw (xtravision-js-sdk.min.js:52:202126)
    at n.render (xtravision-js-sdk.min.js:52:208006)
    at __WEBPACK_DEFAULT_EXPORT__ (init.js:55:1)
```

Even though i set it in the `libData` configuration object. Am I missing something? 
Here is my code:
    
```JS
const props = {
    connectionData: {
	assessment_name: 'SQUATS',
	auth_token: 'auth_token',
	assessmentConfig: {
            reps_threshold: 5,
            grace_time_threshold: 20
	},
	userConfig: {},
	session_id: '12345'
    },
    requestData: {
	isPreJoin: false // if you need to configure education screen then use this, else set to False
    },
    libData: {
	onServerResponse: response => console.log('Server: response', response ),
	videoElementCSS: {}
    }
}

// Render XtraVision React Component
const elem = document.getElementById('xtravision')
ReactDOM.render( React.createElement( AssessmentPage, props ), elem )
```

**Comment by mManishTrivedi** [comment]
Hi @fabrice8,
Thank you for bringing this issue to our attention.  We have fixed the issue and rolled it out. 

Please refer latest updated SDK URL:
`<script src="https://cdn.jsdelivr.net/gh/xtravision-ai/xtravision-js-SDK@1.1.0/xtravision-js-sdk.min.js"> </script>
`
